FROM       tomcat:8
RUN rm -rf /opt/tomcat/webapps/*
ARG WAR_FILE
ADD target/${WAR_FILE} /opt/tomcat/webapps/ROOT.war
ADD docker/*.jar /opt/tomcat/lib/
#ADD docker/server.xml /opt/tomcat/conf/server.xml

EXPOSE 8080
